services:
  - type: web
    name: line-sop-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: CHANNEL_SECRET
        value: <ca1b9decb4235aa49902d26bd8258022>
      - key: CHANNEL_ACCESS_TOKEN
        value: <qJmXLp0ViDZt8ePiuVEuZDyvcs/FpXcN6kzKE2WjnijniXEhhkau1n4N7e2JOx3EJCODGO5rkw1JJbYwaKgfUPHDrp8hAGsNXC28yTTuTuJxwez2CL9jAF7vUyAjNFBiIoWFZ/dzWAI+U3UetRpeMQdB04t89/1O/w1cDnyilFU=>
